FROM debian:buster

RUN apt-get -y update
RUN apt-get -y upgrade

RUN echo "root:server1" | chpasswd
RUN mkdir /var/run/sshd

RUN apt install -y python3 python3-pip ssh git 

RUN pip3 install scapy

WORKDIR /root/

RUN git clone https://github.com/sabarisrinivas-venkatesan/netsploit.git

WORKDIR /root/netsploit
RUN chmod 777 netsploit.sh

ENTRYPOINT [ "/root/whoisscan/netsploit.sh"]
